site_name: SOM-RPM Toolbox
nav:
   - index.md
   - background_theory.md
   - getting_started.md
   - toolbox_structure.md
   - usage_guidelines.md 
   - case_study.md
   - faqs.md
   - glossary.md
   - contact.md
   - attribution.md
   - changelog.md
   - licence.md

theme: readthedocs
use_directory_urls: false

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


